version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 20.8b1
    - 21.4b0
    - 21.4b1
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: twine
    versions:
    - 3.3.0
    - 3.4.0
  - dependency-name: ipython
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
  - dependency-name: mypy
    versions:
    - "0.800"
  - dependency-name: sphinx-rtd-theme
    versions:
    - 0.5.1
  - dependency-name: bleach
    versions:
    - 3.1.4
