from typing import Iterator, List, Union

def read_json(filename: str) -> Union[dict, list]: ...
def read_csv(filename: str) -> List[dict]: ...
def iter_json(filename: str) -> Iterator[dict]: ...
def iter_csv(filename: str) -> Iterator[dict]: ...
